name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! please fill out as much of this as you can
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Description of the bug:"
    validations:
      required: true
  - type: input
    id: discord
    attributes:
      label: Discord Username
      description: Please enter your discord username incase we need more info. Other forms of contact info are valid, but discord is perfered.
      placeholder: ex. Kono Tyran#1865
    validations:
      required: false
  - type: checkboxes
    id: manuallaunch
    attributes:
      label: Manual Minecraft Launch?
      description: Check this box if you were **NOT** using the Archipelago Minecraft Client.
      options:
        - label: Manual Launch
          required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Where did this error take place?
      options:
        - Minecraft Server (Default)
        - Archipelago Minecraft Client
        - Minecraft Client
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell